### ISSUE TITLE
Akroma, Angel of Wrath

### ISSUE THREAD

**Issue by JLYNCH5** [pinky39/grove#2]
Good Afternoon Pinky,  

I downloaded the Zip file and followed your directions for creating this card: Akroma, Angel of Wrath from the Adding-cards-part-1 text file.  I found it had issues with: 
  using Gameplay.Abilities;
  using Gameplay.Characteristics;
  using Gameplay.Misc;

Do these systems not work anymore? I added the text solution I went with below is this Ok?  I tested it playing a match and I noticed Vigilance, and Haste worked,  but I was unable to test it further in game play.  I did see your example for testing it without playing the game in Adding-cards-part-1 is this how you still do it?    

[AkromaAngelOfWrath.txt](https://github.com/pinky39/grove/files/3168528/AkromaAngelOfWrath.txt)

I also noticed you have made major changes to this game through 2015.  Do I have the most up to date version 3.0?  If not, would it be possible to get the most updated version?  

I am absolutely obsessed with this project, I have been looking for guidance on on how to create a game like this for years.  I found here way more than I ever thought possible.  I am basically a Junior Developer looking to get better at coding this type of game.  I can't thank you enough for what I have received.

I am very appreciative of your hard work and I feel your like a mentor to me just by being able to study this project and see how things work.  Thank you so much, this is one of the best gifts I've ever received in my life. 

Sincerely, 
Jeff

**Comment by pinky39** [comment]
Hey Jeff,

glad you like the project. It's been a while since I've done any work on
it. The master branch is for release 3, which was last labeled release. It
contains mostly cards from Urza's block (around 700). Some work was done
after release 3, the goal was to implement some newer cards from M15 and
some other editions. This branch has more than 1100 cards. The new work is
published in pinky branch it should compile ok, the tests also pass I
guess, but the code is not as thouroghly tested as for release 3.

The tutorial you mentioned is a bit out of date, some namespaces were
changed. To help you a bit you should check the implementation of the
following card:

https://github.com/pinky39/grove/blob/aa1ca10d1d62babbf979f94a8801b856fa862c3d/source/Grove/CardsLibrary/MirranCrusader.cs

I suggest that you install git. Fork the game on github to your account.
Then clone the whole repository including the new pinky branch.
The game was developed using VS 2012, you should use the same edition.
The best way to learn is to study the cards already implemented then try to
add new cards that use similar abilities as cards which are already done.

The game also has all the pictures and custom backgrounds, but they were
not published on git since the material is copyrighted.

If you have any more question, send me an email (grega.slavec@gmail.com)
and I'll try to answer.

Have fun,

Gregor
